### ISSUE TITLE
Missing "zlib" dependency

### ISSUE THREAD

**Issue by sunny** [substack/picture-tube#3]
After a fresh install I have a node.js error : "Error: Cannot find module 'zlib'".

After `npm install -g zlib`, it doesn't through the error anymore (although it still doesn't work for me).

**Comment by LinusU** [comment]
zlib should be builtin to Node.js, which version are you using?

https://nodejs.org/api/zlib.html

**Comment by sunny** [comment]
Sorry for not getting back to you earlier, closing this since this issue is waaay to old to matter 😬
